Add files via upload

diff --git a/shadowsocks-debian b/shadowsocks-debian
--- a/shadowsocks-debian
+++ b/shadowsocks-debian
@@ -1,75 +1,94 @@
 #!/bin/bash
+
 ### BEGIN INIT INFO
-# Provides:          shadowsocks
+# Provides:          Shadowsocks
 # Required-Start:    $network $local_fs $remote_fs
 # Required-Stop:     $network $local_fs $remote_fs
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
 # Short-Description: Fast tunnel proxy that helps you bypass firewalls
-# Description:       A secure socks5 proxy, designed to protect your Internet traffic.
+# Description:       Start or stop the Shadowsocks server
 ### END INIT INFO
 
 # Author: Teddysun <i@teddysun.com>
 
-name=shadowsocks
-BIN=/usr/local/bin/ssserver
-conf=/etc/shadowsocks.json
+if [ -f /usr/bin/ssserver ]; then
+    BIN=/usr/bin/ssserver
+elif [ -f /usr/local/bin/ssserver ]; then
+    BIN=/usr/local/bin/ssserver
+fi
+NAME=Shadowsocks
+if [ -f /etc/shadowsocks-python/config.json ]; then
+    CONF=/etc/shadowsocks-python/config.json
+elif [ -f /etc/shadowsocks.json ]; then
+    CONF=/etc/shadowsocks.json
+fi
+RETVAL=0
 
-start(){
-    $BIN -c $conf -d start
-    RETVAL=$?
-    if [ "$RETVAL" = "0" ]; then
-        echo "$name start success"
+check_running(){
+    PID=`ps -ef | grep -v grep | grep -i "${BIN}" | awk '{print $2}'`
+    if [ ! -z "$PID" ]; then
+        return 0
     else
-        echo "$name start failed"
+        return 1
     fi
 }
 
-stop(){
-    pid=`ps -ef | grep -v grep | grep -i "${BIN}" | awk '{print $2}'`
-    if [[ ! -z $pid ]]; then
-        $BIN -c $conf -d stop
+do_start(){
+    check_running
+    if [ $? -eq 0 ]; then
+        echo "$NAME (pid $PID) is already running..."
+        exit 0
+    else
+        $BIN -c $CONF -d start
         RETVAL=$?
-        if [ "$RETVAL" = "0" ]; then
-            echo "$name stop success"
+        if [ $RETVAL -eq 0 ]; then
+            echo "Starting $NAME success"
         else
-            echo "$name stop failed"
+            echo "Starting $NAME failed"
+        fi
+    fi
+}
+
+do_stop(){
+    check_running
+    if [ $? -eq 0 ]; then
+        $BIN -c $CONF -d stop
+        RETVAL=$?
+        if [ $RETVAL -eq 0 ]; then
+            echo "Stopping $NAME success"
+        else
+            echo "Stopping $NAME failed"
         fi
     else
-        echo "$name is not running"
+        echo "$NAME is stopped"
         RETVAL=1
     fi
 }
 
-status(){
-    pid=`ps -ef | grep -v grep | grep -i "${BIN}" | awk '{print $2}'`
-    if [[ -z $pid ]]; then
-        echo "$name is not running"
-        RETVAL=1
+do_status(){
+    check_running
+    if [ $? -eq 0 ]; then
+        echo "$NAME (pid $PID) is running..."
     else
-        echo "$name is running with PID $pid"
-        RETVAL=0
+        echo "$NAME is stopped"
+        RETVAL=1
     fi
+}
+
+do_restart(){
+    do_stop
+    do_start
 }
 
 case "$1" in
-'start')
-    start
+    start|stop|restart|status)
+    do_$1
     ;;
-'stop')
-    stop
-    ;;
-'status')
-    status
-    ;;
-'restart')
-    stop
-    start
-    RETVAL=$?
-    ;;
-*)
+    *)
     echo "Usage: $0 { start | stop | restart | status }"
     RETVAL=1
     ;;
 esac
+
 exit $RETVAL
